// place files you want to import through the `$lib` alias in this folder.
const quotes = [
	'Oh, shit. Now, they\'re all over. Swarm out, flow out, drop off, please.',
	'Or have these. Look in another room, but, oh, we hit our slope, this whole moonway. Go, Philip Fair.',
	'Stir up the, and then you use to merriments. Awaken the pert and nimble spirit of mirth. Power, I root you in my soul, and one thy love, doing the Indians, power, what thee, and another key, with pop, with a trial, and with road.',
	'How do you think he is starting out? Thanks for the deals. What\'s the news?',
	'Full of vacation, come out and think against my child, my mom... This my noble lord, this man said America. my roulette and so. To find out, so try hard.',
	'For me, you, to me, to start my shit. Even so, she will act here for veterinary. I beg the age of moments or apples.',
	'I so far. Yeah, for death. Party, hurry up.',
	'Big raspberry, you, poor mother, you, as it not, when you torture you today, you are adding warm in rock. By her own, in the end, in her power, three, two, four, three. To me, this is already done.',
	'So much for Santa. Rather, your eyes must be important. What?',
	'I\'m doing speak your best part of me. I will not I need. Tonight, the teacher, I said, I mean, the worst, I mean, before me in this case, I refuse to have Demetrius.',
	'Either the God is dead, or sojourn for ever the society of men. Therefore, there are questions on God. Though you do, exact valuable love, for if you yield God to your mother\'s reporting, and endure the liberty of enough, pride\'s meat is shaking forward, for you, you live.',
	'A bear, since they\'re all your mother, can\'t face him to the cold, for the moon. Christ, class, are they that master so good? But, I don\'t know, they\'ve done it. earlier And now the pointer is on the floor.',
	'Rotan lives, and now, you see all one. Someone like a so late, so diamond! And I go to lose my bird\'s mouth up, and switch lordship.',
	'They\'re wishing, you know, I told them, that\'s not keep sovereignty. And by then, the stealing day, which works fine, love in me, for everlasting bomb of fellow. On that day, be the repair to die or disobedient to your mother, go, rest away to beaches, as he would.',
	'Boron, Diana\'s love to protest, bride, therapy, and a single black. Relent, sweet, hurry up, and my favor, give my crazy title. My, something right, you have your mother\'s love to be true.',
	'We have her me out. Do you marry her? Sure, I did.',
	'True, we have another. And we\'re flying by myself. And she is mine.',
	'Oh am I writing for her. I do a state. I\'m Ditri.',
	'I am. My Lord. As well derived as he, as well possessed, my lover is more than his, my fortunes, everywhere is fairly right.',
	'I\'m good advantage as to these risks. Which is more than all these notes can be? I am love of beauty areia.',
	'Why should not I then prosecute my rights? To be with us, well, not just to his head, then not to danger\'s daughter, Helena, and Wonder Soul. And she, sweet Brady, don\'t, the mountain we don\'t.',
	'Don\'t do that idolatry upon this spotted and inconstant man.',
	'I must confess I have heard as much. And look to me, she thought to have both hero.',
	'But being so overclosed of self affairs, my mind is new. But come to me. And come to me.',
	'High, some high school people. For you, fair friend. Look you on yourself, take your fancies to your mother\'s fit.',
	'For us the law about this, you you are pitched by no means we can extend it. To death, to vow, to single God. Come, Paula.',
	'What\'s your mother? Demetrius and Demetrius. Go!',
	'will follow. Oh, now, my love. She\'s so pale.',
	'Keep seeing it. We\'re here. Send.',
	'Mom, not Mom. I forgot so much, not asking. No, please, it\'s a customary problem.',
	'It\'s not, it\'s not, it\'s... is it? Com roller. They\'re both here, me, from now.',
	'I have to go yet. And now it\'s a who is smiling, but she has no child. suddenly son. Okay, I\'m marrying these.',
	'Get to the place for Charlotte to be locked head off. There she was. We\'re sweet, like, keep it strongly, folks. like the best heroin with the golden hell.',
	'By the simplicity of the yourself, I promise, it is soul and prosper, love. By all the mast and equiliment have broken, nevertheless, ever wanted to go. Now, safety is now...',
	'Like, he... What? What?',
	'What? We already call you there. The bear gonna stay.',
	'The music your hands. Oh, happy day, day, day. Your eyes are low stars.',
	'I don\'t talk, sweet air, we\'re too little large, shit over here. When we just see, all my love up here, say, this is catching all your fame, so yours, and I catch fair birmia, and I go. My ears should catch her voice.',
	'My eye, your eye, my function, and yours for the sweet melody, for the world mine, Dimitri, is being made. the rest I will be to you family. Oh, teach me how to look it from what arches sway the emotionally. Demetrius, you are too proud of it.',
	'He\'s still home, and you\'re proud. My! You cursed, get to me.',
	'The more I hate, the more the goals, the more I love, the more he hates me. It daddy. The light, so all along, with nothing more easy to have...',
	'The heat is covered. my face. My stand and myself quiet and free. time I It\'s probably my grace, it\'s heaven, unto a hell. Helen, you are mine.',
	'In the one, we\'re off to you and I, of 20, years, and, and, and, and, and, and, and, and, and, and, and, and, and, and, and, and, stranger companies. There were hours to be, say, love. Pray that for us.',
	'And it\'s good, love, save that Demetrius. He our. And that was my heart, yeah. Hello?us on view. as fair as she. But what a best Demeri\' not so know what all we do know that the airsing us hurt eyes so I. Things, face, and vile will do no qualities. and do...',
	'What will come the eyes of the blue belong, and therefore, I mean, human, be in mind. nor have love mine for any age. We even know eyes, figure, unbeat, face, and, therefore, the love that\'s being a child. Because we enjoy things, people, off, control, as well as the boy, his name, themselves, forswear.',
	'So look all I love is burger everywhere. Where? I, he nailed them both, because it was only mine.',
	'And when the tail\'s out, he for her, yes, yes, so he\'s a doll, he shouts all, didn\'t know. I don\'t know, because... of their hurry, his wife, and to live, to be more around, to see her, and with it, his love... Yes.',
	'But my scissor and back again! Let\'s go.',
];

export default quotes;