// place files you want to import through the `$lib` alias in this folder.
const quotes = [
	'Or have these. Look in another room, but, oh, we hit our slope, this whole moonway. Go, Philip Fair.',
	'Stir up the, and then you use to merriments. Awaken the pert and nimble spirit of mirth.',
	'Power, I root you in my soul, and one thy love, doing the Indians,',
	'power, what thee, and another key, with pop, with a trial, and with road.',
	'How do you think he is starting out? Thanks for the deals. What\'s the news?',
	'Full of vacation, come out and think against my child, my mom...',
	'This my noble lord, this man said America. my roulette and so. To find out, so try hard. For me, you, to me, to start my shit.',
	'Even so, she will act here for veterinary.',
	'I beg the age of moments or apples.',
	'I so far. Yeah, for death. Party, hurry up. Big raspberry,',
	'you, poor mother, you, as it not, when you torture you today, you are adding warm in rock. By her own, in the end, in her power, three, two, four, three.',
	'So much for Santa. Rather, your eyes must be important. What?',
	'I\'m doing speak your best part of me. I will not I need.',
	'Tonight, the teacher, I said, I mean, the worst, I mean, before me in this case, I refuse to have Demetrius.',
	'Either the God is dead,',
	'Therefore, there are questions on God. Though you do, exact valuable love, for if you yield God to your mother\'s reporting, and endure the liberty of enough,',
	'pride\'s meat is shaking forward, for you, you live.',
	'A bear, since they\'re all your mother, can\'t face him to the cold, for the moon.',
	'Christ, class, are they that master so good?',
	'But, I don\'t know, they\'ve done it. earlier And now the pointer is on the floor.',
	'Rotan lives, and now, you see all one. Someone like a so late, so diamond! And I go to lose my bird\'s mouth up, and switch lordship.',
	'They\'re wishing, you know, I told them, that\'s not keep sovereignty.',
	'And by then, the stealing day, which works fine, love in me, for everlasting bomb of fellow.',
	'go, rest away to beaches, as he would.',
	'Boron, Diana\'s love to protest, bride, therapy, and a single black.',
	'Relent, sweet, hurry up, and my favor, give my crazy title.',
	'We have her me out. Do you marry her? Sure, I did.',
	'True, we have another. And we\'re flying by myself. And she is mine.',
	'Oh am I writing for her. I do a state. I\'m Ditri. I am.',
	'My Lord. As well derived as he, as well possessed, my lover is more than his, my fortunes, everywhere is fairly right.',
	'I\'m good advantage as to these risks. Which is more than all these notes can be? I am love of beauty areia.',
	'Why should not I then prosecute my rights?',
	'To be with us, well, not just to his head, then not to danger\'s daughter, Helena, and Wonder Soul. And she, sweet Brady, don\'t, the mountain we don\'t.',
	'Don\'t do that idolatry',
	'And look to me, she thought to have both hero.',
	'But being so overclosed of self affairs, my mind is new.',
	'But come to me. And come to me.',
	'High, some high school people. For you, fair friend.',
	'Look you on yourself, take your fancies to your mother\'s fit.',
	'For us the law about this, you you are pitched by no means we can extend it.',
	'To death, to vow, to single God.',
	'Come, Paula. What\'s your mother? Demetrius and Demetrius. Go! will follow.',
	'Oh, now, my love. She\'s so pale. Keep seeing it. We\'re here. Send. Mom, not Mom. I forgot so much, not asking.',
	'No, please, it\'s a customary problem. It\'s not, it\'s not, it\'s... is it? Com roller.',
	'They\'re both here, me, from now. I have to go yet. And now it\'s a who is smiling, but she has no child.',
	'suddenly son. Okay, I\'m marrying these.',
	'Get to the place for Charlotte to be locked head off.',
	'There she was. We\'re sweet, like, keep it strongly, folks. like the best heroin with the golden hell.',
	'By the simplicity of the yourself, I promise, it is soul and prosper, love.',
	'By all the mast and equiliment have broken, nevertheless, ever wanted to go.',
	'Now, safety is now... Like, he... What? What? What? We already call you there. The bear gonna stay.',
	'The music your hands. Oh, happy day, day, day. Your eyes are low stars.',
	'I don\'t talk, sweet air, we\'re too little large, shit over here.',
	'When we just see, all my love up here, say, this is catching all your fame, so yours, and I catch fair birmia, and I go.',
	'the rest I will be to you family.',
	'Oh, teach me how to look it from what arches sway the emotionally.',
	'Demetrius, you are too proud of it. He\'s still home, and you\'re proud. My! You cursed, get to me.',
	'The more I hate, the more the goals, the more I love, the more he hates me. It daddy.',
	'The light, so all along, with nothing more easy to have...',
	'The heat is covered. my face. My stand and myself quiet and free.',
	'time I It\'s probably my grace, it\'s heaven, unto a hell. Helen, you are mine.',
	'In the one, we\'re off to you and I, of 20, years,',
	'and, and, and, and, and, and, and, and, and, and, and, and, and, and, and, and, stranger companies.',
	'There were hours to be, say, love. Pray that for us. And it\'s good, love, save that Demetrius.',
	'He our. And that was my heart, yeah.',
	'Things, face, and vile will do no qualities. and do...',
	'What will come the eyes of the blue belong, and therefore,',
	'I mean, human, be in mind. nor have love mine for any age.',
	'We even know eyes, figure, unbeat, face, and, therefore, the love that\'s being a child.',
	'Because we enjoy things, people, off, control, as well as the boy, his name, themselves, forswear.',
	'So look all I love is burger everywhere. Where?',
	'I, he nailed them both, because it was only mine.',
	'And when the tail\'s out, he for her, yes, yes, so he\'s a doll, he shouts all, didn\'t know.',
	'I don\'t know, because... of their hurry, his wife, and to live, to be more around, to see her, and with it, his love...',
	'Yes. But my scissor and back again! Let\'s go.',
	'Huzzah!! Mom! No, are we in here?',
	'Sure, that\'s small, Japanese...',
	'And I\'m every quarters in the room. Hearing the pool...',
	'Everybody, talking, throw hatches, and she put in our Indian foods, for the zoo, and doctor, on his wedding day and night.',
	'Per. Good here. Stay what you\'re playing. You\'re gone.',
	'They read the name of the directors, and so drugs or boys. Mary?',
	'Power play is. Aw. And we\'ll crawl back, Parrot, and Vinnie. A very good piece of work.',
	'Yeah, sure, you add in America. Now, whip in your queens, call water, I can find this roll.',
	'Fast or spread yourselves.',
	'I think we should, we should get, like, a mirror. That\'s good.',
	'And around that, all of you. Here.ver. Right.',
	'Man, what\'s hot? I can pull, right? See? Do you think water doesn\'t have to play here, man?',
	'What is it? Hold on. Or forward. Hey, what? Hey, what\'s happening? This palace for love.. Their eyes, I will move more.',
	'Rat. T shirt. I, very, rarely. cross And take your heart. For a month...',
	'Now, we didn\'t go back to our science... This is fairly vain.',
	'Stells, man. You do this. Huh? You must take this young way. What is? tonight?',
	'Hey, that\'s hear. Let me know, my woman. I\'m fearful. Why.',
	'Whereabouts, you can feed it to all of you.',
	'Hey, I\'m a father, piece of meat. I\'ll see your mom.. No, no, no, no.',
	'Must play here, Rick. I. Well? Taylor. Beautiful. Sparkling, you must make it, you mother.',
	'Calm down, the finger. You here with father.. Do the daughter, cute, align, pops.',
	'Hey, go through the plate bin. You, like, for me. Pray, you, you, you, me, cry, flawless, study',
	'Three, two, three. Not control. But me, I know, I do, too.',
	'I will horn I will do. I am a whore, and I will make you feel safe.',
	'Look, beautiful, Morgan! Like, true, more, good. too terrible.',
	'Right about it, and then they eat in a tree, and bring up the AIO. Now!',
	'I aggravate my voice. That\'s you. fucking not. I will draw you, and for a nightingale.',
	'No, no. Come? You\'re on a compliment. It\'s a wee, big man, one, two, please, one.',
	'He will love it, love it, like this. Therefore, you...',
	'Hey, Karen.',
	'Wow. I will, okay?',
	'All right. We\'re faster. Here are your parts.',
	'I am two... And three of you... Three box you... and be dial... Come on... Come, little mile at the counter.',
	'Mom, me, me, like, little dog. I bring you... fail me not.',
	'We will meet. They were... Okay. Hey. Hey.',
	'Here you go. And do go, for now. Not enough.',
	'Oh, no, no, no. Oh, my God. Sorry I got you off.',
	'Sh Yes! I guess I\'ll take you. Sh Guys. Take pictures. Let\'s go. Are you free?',
	'Let me call you. Go, go, go, go. Just go first., Master.',
	'You want your laundry here? Over, over, over, and over.',
	'And I serve the Dairy Queen.',
	'the tree Over hill over bush World water over heart over of blood on fire And they\'re cold, cold, cold, sweet.',
	'Go, be your beast, merry neighbors. In their freckle, in their feet more.',
	'Over hill, over long, dish, world smile, over dark, over hail, grow blood.',
	'Sparrow down on my spirit, I\'ll be gone. Unseen it all, you\'re off, you\'re on.',
	'They made us in reels here tonight!',
	'Baby, the baby is not going to fight, throw over on fish,',
	'happy shell, and giraffe.',
	'The lovely boy, so... You never have so sweet a change, like, and just go wrong, perhaps, the child, and make the constraints, the church, the poor smile.',
	'G old my boy. and all for joy.',
	'And now, again, we, a girls are running about thousand years, a single spell of sheep.',
	'I couldn\'t be... You heard him stink, shake, and making plates, or else you\'re that shrewd and name striped.',
	'How r Goodfellow Or not you, he that friends made into the villagery, skim milk, and sometimes labor in the corn, and move it, make the bathroom cross my turn.',
	'And so is I, make the drinks pair no farm. missing nutcers laughing at their water.',
	'We hold you have off into our work. Are you not eating? That\'s biggest, right?',
	'I am the very wanderer of the night.',
	'I just sit over on and make him smile when I\'m a fast and be fed or sweet,',
	'I... Now you left this up to the old.',
	'Some let this and then she drinks it into I the for you!',
	'off time for TV So I remember downtownle she parris and fall into a cup and the whole quiet there and laughs and accident ever then he swear. there.',
	'Barry, here comes over and hear my mistress what you mom.',
	'Come on, Tanya. What? Tell us over on? Very, deepest, I will swore, Miss Bennett.',
	'Terror, grass. Coming on time, the Lord. I must be likely. But I know that\'s all, you\'re better.',
	'And shakes work at all days, they all have born and first looked ever. Why are not here?',
	'I\'m gonna fart to see you in the yoga bath soup.',
	'You\'re about to be in missions and warriors, love. It\'s easy, so sweet, ready.',
	'And you come to give them bed joint and prosperity. Hope has thou for shame, Tom. Glen to our friend.',
	'I\'m going, ah, no, my love.',
	'He got the forgeries of jealousy.',
	'But never, since the film of her spring, met me on him until, for me. I gave you a thousand, or by Washington, or on the beach in New Orleans...',
	'To dance, or bring it to the wind, but we\'ve done... That has to start our sport.',
	'Therefore, the winds, piping to us in vain, as in revenge, has summed up from the sea, the taint, long, long, and land, and, oh, really, so proud.',
	'And they have opened for their ovens. The human mortals, what? cheer no kn now we faail or bless than woman And our anger washing all the air aboutat feet And always.',
	'The summer, the child, the autumn, and the baby... Why the baby, now, which is which?',
	'And this big prodigy of evil come from our defeat from our possession.',
	'We are the parent and original.',
	'Do you imagine them? It lies in you. Why, such a time you cross your Oberon, and you beg a little changing boy to be my benchman.',
	'Set your heart out breath! better that time.',
	'And the passion by',
	'But she, being mortal at that point, and die, and for her sake, do I fear of her boy, for her sake?',
	'I will not part with him.',
	'How long, Mr. William, did you stay? For chance is wedding there.',
];

export default quotes;